### ISSUE TITLE
Implement humidex module from ladybug-legacy code

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-comfort#30]
As many ladybug legacy users know, @stgeorges did a phenomenal job writing code for [calculating humidex in ladybug-leagcy](https://github.com/ladybug-tools/ladybug-legacy/blob/master/src/Ladybug_Thermal%20Comfort%20Indices.py#L627-L654). At this point, it would be great to further clean + document this code and and integrate it into ladybug-comfort such that other developers can easily calculate humidex using the [ladybug-comfort package on PyPI](https://pypi.org/project/ladybug-comfort/) and view documentation about the model within the [online documentation for this repo](https://www.ladybug.tools/ladybug-comfort/docs/ladybug_comfort.html).

You can see that I have already done an example of translating one of the models from @stgeorges 's components with the [Heat Index (HI) in this library](https://github.com/ladybug-tools/ladybug-comfort/blob/master/ladybug_comfort/hi.py).  This was translated over from the [heat index function in the thermal indices component](https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Thermal%20Comfort%20Indices.py#L572-L610) and the references in the docstring came from on [the wikipedia page for heat index](https://en.wikipedia.org/wiki/Heat_index).

I am posting this issue here in the event that someone sees it and decides that they would like to take up the mantle of transferring this code, documenting it, and getting it to conform to [PEP8](https://www.python.org/dev/peps/pep-0008/).  If anyone has interest, please feel free to post on this issue.

**Comment by matt-blodgett** [comment]
Hi @chriswmackey 

I'd like to try this out by following your example. 
I think the requirements are straightforward.

**Comment by chriswmackey** [comment]
Thanks for addressing this @matt-blodgett !
